-- ETC sweep transactions table
CREATE TABLE IF NOT EXISTS etc_sweep_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    hot_address VARCHAR(128),
    cold_address VARCHAR(128),

    tx_hash VARCHAR(128),
    submitted BOOLEAN NOT NULL,

    hot_balance_wei VARCHAR(78),
    amount_sent_wei VARCHAR(78),
    gas_used_wei VARCHAR(78),

    updated_hot_balance_wei VARCHAR(78),

    message TEXT
);

CREATE INDEX IF NOT EXISTS idx_etc_sweep_transactions_created_at
    ON etc_sweep_transactions (created_at);

CREATE INDEX IF NOT EXISTS idx_etc_sweep_transactions_tx_hash
    ON etc_sweep_transactions (tx_hash);
