CREATE TABLE IF NOT EXISTS doge_sweep_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    hot_address VARCHAR(128),
    cold_address VARCHAR(128),

    tx_id VARCHAR(128),
    submitted BOOLEAN NOT NULL,

    hot_balance NUMERIC(20, 8),
    amount_sent NUMERIC(20, 8),

    updated_hot_balance NUMERIC(20, 8),

    message TEXT
);

-- Existing DBs: make sure the new column exists.
ALTER TABLE doge_sweep_transactions
    ADD COLUMN IF NOT EXISTS updated_hot_balance NUMERIC(20, 8);

CREATE INDEX IF NOT EXISTS idx_doge_sweep_transactions_created_at
    ON doge_sweep_transactions (created_at);

CREATE INDEX IF NOT EXISTS idx_doge_sweep_transactions_tx_id
    ON doge_sweep_transactions (tx_id);
