spring.application.name=pool_ser
# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pool_ser
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
# Set before running:
# ALCHEMY_HTTP_URL=... (you know env variable)
# SWEEPER_HOT_KEY=0x... (you know env variable)
# SWEEPER_COLD_ADDRESS=0x... (you know env variable)