ALTER TABLE sweeps
    ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_error VARCHAR(512),
    ADD COLUMN IF NOT EXISTS last_checked_at TIMESTAMPTZ;
